const catalogoCanciones = [
    { nombre: "MORENA", favorito: false },
    { nombre: "MIAMI", favorito: false },
    { nombre: "WOMAN", favorito: false },
    { nombre: "SECRETO", favorito: false },
    { nombre: "NUNCA IMAGINE", favorito: false },
    { nombre: "CAMPEÓN", favorito: false },
    { nombre: "COSITAS", favorito: false },
    { nombre: "DIME", favorito: false },
    { nombre: "PENSÁNDOTE", favorito: false },
    { nombre: "JAMAICA", favorito: false },
    { nombre: "MEDELLÍN", favorito: false },
    { nombre: "LEJANÍA", favorito: false },
    { nombre: "HAY AMORES", favorito: false },
    { nombre: "JORDAN", favorito: false },
    { nombre: "WASA WASA", favorito: false },
    { nombre: "MONASTERY", favorito: false },
    { nombre: "CHUPABLE", favorito: false },
    { nombre: "MUJERIEGO", favorito: false },
    { nombre: "Q'HUBO BEBÉ", favorito: false },
    { nombre: "MÍRATE BIEN", favorito: false },
    { nombre: "PRENDE Y APAGA", favorito: false },
    { nombre: "NIÑA DE MIS SUEÑOS", favorito: false },
    { nombre: "CLÁSICO", favorito: false },
    { nombre: "AMOR DE UNA NOCHE", favorito: false },
    { nombre: "NEA", favorito: false },
    { nombre: "EL PAN DE ESTEFANÍA", favorito: false },
    { nombre: "OE OE OE", favorito: false },
    { nombre: "LÁTIGO", favorito: false },
    { nombre: "PIKETE", favorito: false },
    { nombre: "QUÉ MÁS PUES?", favorito: false },
    { nombre: "METAS", favorito: false },
    { nombre: "BÉSAME", favorito: false },
    { nombre: "MARBELLA", favorito: false },
    { nombre: "GHETTO STAR", favorito: false },
    { nombre: "QUEMA", favorito: false },
    { nombre: "EL PICHÓN", favorito: false },
    { nombre: "X 1 BESO", favorito: false },
    { nombre: "CORAZÓN ROTO (REMIX / PT. 3)", favorito: false },
    { nombre: "PLEBITA", favorito: false },
    { nombre: "EL CANTANTE DEL GHETTO", favorito: false },
    { nombre: "PUEBLO DE MEDALLO", favorito: false },
    { nombre: "NCA", favorito: false },
    { nombre: "GATA G", favorito: false },
    { nombre: "MALEANTE", favorito: false },
    { nombre: "FRESKI", favorito: false },
    { nombre: "FENDI", favorito: false },
    { nombre: "MODELITO", favorito: false },
    { nombre: "BIG DREAMS", favorito: false },
    { nombre: "ENVIGADO", favorito: false },
    { nombre: "JORDAN REMIX", favorito: false },
    { nombre: "NADA CAMBIO", favorito: false },
    { nombre: "MI DIABLA Y MI DIOSA", favorito: false },
    { nombre: "LOS CAPOS", favorito: false },
    { nombre: "XL", favorito: false },
    { nombre: "RICH RAPPERS", favorito: false },
    { nombre: "EL RITMO QUE NOS UNE", favorito: false },
    { nombre: "+57", favorito: false },
    { nombre: "FDSR", favorito: false },
    { nombre: "SQ", favorito: false },
    { nombre: "SENDÉ", favorito: false },
    { nombre: "REBECCA", favorito: false },
    { nombre: "UN TRIO", favorito: false },
    { nombre: "PA Q VUELVA", favorito: false },
    { nombre: "MENOS EL CORA", favorito: false },
    { nombre: "DEJATE VER", favorito: false },
    { nombre: "CASITA EN LA MONTAÑA", favorito: false },
    { nombre: "AYOME:(", favorito: false },
    { nombre: "GL", favorito: false },
    { nombre: "LOBA", favorito: false },
    { nombre: "BOMBASTIK<3", favorito: false },
    { nombre: "SANKA", favorito: false },
    { nombre: "OFICIAL", favorito: false },
    { nombre: "YO VIENDO", favorito: false },
    { nombre: "OJALÁ", favorito: false },
    { nombre: "INMERSO", favorito: false },
    { nombre: "EXCLUSIVA", favorito: false },
    { nombre: "MODO LEYENDA", favorito: false },
    { nombre: "AY MI PAPÁ", favorito: false },
    { nombre: "LA MINI", favorito: false },
    { nombre: "BOTAPAFO", favorito: false },
    { nombre: "BA BA BAD REMIX", favorito: false },
    { nombre: "SI ME PREGUNTARAN", favorito: false },
    { nombre: "AZOTA MAMASOTA", favorito: false },
    { nombre: "LA VILLA", favorito: false },
    { nombre: "SAI", favorito: false },
    { nombre: "HABLA CLARO", favorito: false },
    { nombre: "PELINEGRA", favorito: false },
    { nombre: "MONA", favorito: false },
    { nombre: "MODO BESTIAL", favorito: false },
    { nombre: "CHAMPION", favorito: false },
    { nombre: "UNA A LA VEZ", favorito: false },
    { nombre: "DALMATION", favorito: false },
    { nombre: "MELO", favorito: false },
    { nombre: "GWA", favorito: false },
    { nombre: "MEDETOWN", favorito: false },
    { nombre: "BENGALÍ", favorito: false },
    { nombre: "PAL AGUA", favorito: false },
    { nombre: "VIERNES", favorito: false },
    { nombre: "TONTO", favorito: false },
    { nombre: "OMERTA", favorito: false },
    { nombre: "SE LE VE", favorito: false },
    { nombre: "GANAS REMIX", favorito: false },
    { nombre: "DESAHÓGATE", favorito: false },
    { nombre: "PA' LA SECA", favorito: false },
    { nombre: "CHÉVERE (PREMIUM REMIX)", favorito: false }
];